from . import help
from . import start
from . import work_m
from . import balans_menu
from . import click_menu
from . import settings_menu
from . import kabenet_menu
from . import Qoidalar_menu
from . import contact_menu
from . import Hisob_menu
from . import echo